# Generated by Django 4.1.3 on 2022-11-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registers',
        ),
    ]
