# Generated by Django 4.1.3 on 2022-12-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0004_folder_date_folder_is_delete_folder_is_fav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderfile',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dmsapp.folder'),
            preserve_default=False,
        ),
    ]
