# Generated by Django 4.1.3 on 2022-12-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0007_remove_profile_email_remove_profile_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
