# Generated by Django 4.1.3 on 2022-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0008_alter_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='user/'),
        ),
    ]
