# Generated by Django 4.1.3 on 2022-12-22 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmsapp', '0011_alter_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_when', models.DateTimeField(blank=True, null=True)),
                ('times_open', models.CharField(blank=True, max_length=30, null=True)),
                ('open_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shear_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmsapp.file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
