# Generated by Django 4.1.3 on 2022-12-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0013_alter_fileview_opened_when'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileview',
        ),
    ]
